variables:
  HARBOR_REGISTRY: hb.sepehr.it
  HARBOR_PROJECT: infra
  HARBOR_REPO: hls-converter

  K8S_NAMESPACE: infra
  K8S_PROJECT_NAME: hls-converter
  INGRESS_DOMAIN: hls.sepehritg.ir

  IMAGE_REPO: $HARBOR_REGISTRY/$HARBOR_PROJECT/$HARBOR_REPO
  IMAGE: $IMAGE_REPO:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  tags:
    - public
  script:
    - echo "$HARBOR_PASS" | docker login $HARBOR_REGISTRY -u "$HARBOR_USER" --password-stdin
    - docker build -t $IMAGE .
  only:
    - main

publish:
  stage: publish
  tags:
    - public
  script:
    - echo "$HARBOR_PASS" | docker login $HARBOR_REGISTRY -u "$HARBOR_USER" --password-stdin
    - docker push $IMAGE
  only:
    - main

deploy:
  stage: deploy
  tags:
    - public
  script:
    - sed -i "s/{{ NAMESPACE }}/$K8S_NAMESPACE/g" kube.yml
    - sed -i "s/{{ PROJECT_NAME }}/$K8S_PROJECT_NAME/g" kube.yml
    - sed -i "s|{{ IMAGE }}|$IMAGE|g" kube.yml
    - sed -i "s|{{ INGRESS_DOMAIN }}|$INGRESS_DOMAIN|g" kube.yml
    - mkdir -p ~/.ssh && echo "$K8S_SSH_KEY" > ~/.ssh/k8s_key && chmod 600 ~/.ssh/k8s_key
    - ssh -i ~/.ssh/k8s_key -o StrictHostKeyChecking=no -p 1164 root@194.180.11.64 "kubectl apply --validate=false -f -" < kube.yml
  only:
    - main
